name: magface
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-learn=1.2.2
  - pillow=9.5.0
  - tqdm=4.65.0
  - pip
  - pip:
    - mxnet-cu112==1.9.1
    - termcolor==2.3.0
    - opencv-python==4.8.0.74
